### ISSUE TITLE
E/UncaughtException: java.lang.UnsatisfiedLinkError: No implementation found for void 

### ISSUE THREAD

**Issue by anonym2** [likaiyuan559/TikTokDemo#11]
Hi Sir I got this error from the code implemented in my app , what can I do for fix  it ?

**Comment by anonym2** [comment]
Looks like its the file  libheyhou_video who make trouble can you help me fix it please

**Comment by likaiyuan559** [comment]
Can you provide specific information？

**Comment by anonym2** [comment]
Here is my LogCat  


2019-05-09 22:24:13.585 507-27262/? E/libc: Access denied finding property "camera.p2tpipedump.enable"
2019-05-09 22:24:13.598 507-27262/? E/libc: Access denied finding property "camera.dumpbuffer.enable"
2019-05-09 22:24:13.598 507-27262/? E/libc: Access denied finding property "camera.dumpbuffer.enable"
2019-05-09 22:24:13.611 27142-27142/aftercorp.final_flash E/zygote: No implementation found for int aftercorp.final_flash.Newshow.video.HeyhouRecorder.start(java.lang.String, int, int, int, int, int) (tried Java_aftercorp_final_1flash_Newshow_video_HeyhouRecorder_start and Java_aftercorp_final_1flash_Newshow_video_HeyhouRecorder_start__Ljava_lang_String_2IIIII)
2019-05-09 22:24:13.612 27142-27142/aftercorp.final_flash E/InputEventReceiver: Exception dispatching input event.
2019-05-09 22:24:13.612 27142-27142/aftercorp.final_flash E/MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
2019-05-09 22:24:13.620 27142-27142/aftercorp.final_flash E/MessageQueue-JNI: java.lang.UnsatisfiedLinkError: No implementation found for int aftercorp.final_flash.Newshow.video.HeyhouRecorder.start(java.lang.String, int, int, int, int, int) (tried Java_aftercorp_final_1flash_Newshow_video_HeyhouRecorder_start and Java_aftercorp_final_1flash_Newshow_video_HeyhouRecorder_start__Ljava_lang_String_2IIIII)
        at aftercorp.final_flash.Newshow.video.HeyhouRecorder.start(Native Method)
        at aftercorp.final_flash.Newshow.video.HeyhouRecorder.startRecord(HeyhouRecorder.java:80)
        at aftercorp.final_flash.Newshow.record.presenter.RecordVideoPresenter.startRecord(RecordVideoPresenter.java:596)
        at aftercorp.final_flash.Newshow.record.RecordVideoActivity$5.onEventDown(RecordVideoActivity.java:343)
        at aftercorp.final_flash.Newshow.record.weight.CircleRecordView.onTouchEvent(CircleRecordView.java:189)
        at android.view.View.dispatchTouchEvent(View.java:11819)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3027)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2627)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3027)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2627)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3027)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2627)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3027)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2627)
        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:601)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1839)
        at android.app.Activity.dispatchTouchEvent(Activity.java:3321)
        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:552)
        at android.view.View.dispatchPointerEvent(View.java:12063)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4976)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4786)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4318)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4371)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4337)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4464)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4345)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4521)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4318)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4371)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4337)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4345)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4318)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6912)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6886)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6843)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7030)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:186)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:325)
        at android.os.Looper.loop(Looper.java:142)
        at android.app.ActivityThread.main(ActivityThread.java:6537)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:857)
2019-05-09 22:24:13.621 27142-27142/aftercorp.final_flash D/AndroidRuntime: Shutting down VM
2019-05-09 22:24:13.631 27142-27142/aftercorp.final_flash E/AndroidRuntime: FATAL EXCEPTION: main
    Process: aftercorp.final_flash, PID: 27142
    java.lang.UnsatisfiedLinkError: No implementation found for int aftercorp.final_flash.Newshow.video.HeyhouRecorder.start(java.lang.String, int, int, int, int, int) (tried Java_aftercorp_final_1flash_Newshow_video_HeyhouRecorder_start and Java_aftercorp_final_1flash_Newshow_video_HeyhouRecorder_start__Ljava_lang_String_2IIIII)
        at aftercorp.final_flash.Newshow.video.HeyhouRecorder.start(Native Method)
        at aftercorp.final_flash.Newshow.video.HeyhouRecorder.startRecord(HeyhouRecorder.java:80)
        at aftercorp.final_flash.Newshow.record.presenter.RecordVideoPresenter.startRecord(RecordVideoPresenter.java:596)
        at aftercorp.final_flash.Newshow.record.RecordVideoActivity$5.onEventDown(RecordVideoActivity.java:343)
        at aftercorp.final_flash.Newshow.record.weight.CircleRecordView.onTouchEvent(CircleRecordView.java:189)
        at android.view.View.dispatchTouchEvent(View.java:11819)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3027)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2627)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3027)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2627)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3027)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2627)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3027)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2627)
        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:601)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1839)
        at android.app.Activity.dispatchTouchEvent(Activity.java:3321)
        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:552)
        at android.view.View.dispatchPointerEvent(View.java:12063)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4976)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4786)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4318)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4371)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4337)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4464)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4345)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4521)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4318)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4371)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4337)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4345)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4318)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6912)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6886)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6843)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7030)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:186)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:325)
        at android.os.Looper.loop(Looper.java:142)
        at android.app.ActivityThread.main(ActivityThread.java:6537)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:857)
2019-05-09 22:24:13.636 27142-27142/aftercorp.final_flash E/UncaughtException: java.lang.UnsatisfiedLinkError: No implementation found for int aftercorp.final_flash.Newshow.video.HeyhouRecorder.start(java.lang.String, int, int, int, int, int) (tried Java_aftercorp_final_1flash_Newshow_video_HeyhouRecorder_start and Java_aftercorp_final_1flash_Newshow_video_HeyhouRecorder_start__Ljava_lang_String_2IIIII)
        at aftercorp.final_flash.Newshow.video.HeyhouRecorder.start(Native Method)
        at aftercorp.final_flash.Newshow.video.HeyhouRecorder.startRecord(HeyhouRecorder.java:80)
        at aftercorp.final_flash.Newshow.record.presenter.RecordVideoPresenter.startRecord(RecordVideoPresenter.java:596)
        at aftercorp.final_flash.Newshow.record.RecordVideoActivity$5.onEventDown(RecordVideoActivity.java:343)
        at aftercorp.final_flash.Newshow.record.weight.CircleRecordView.onTouchEvent(CircleRecordView.java:189)
        at android.view.View.dispatchTouchEvent(View.java:11819)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3027)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2627)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3027)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2627)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3027)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2627)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3027)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2627)
        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:601)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1839)
        at android.app.Activity.dispatchTouchEvent(Activity.java:3321)
        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:552)
        at android.view.View.dispatchPointerEvent(View.java:12063)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4976)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4786)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4318)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4371)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4337)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4464)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4345)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4521)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4318)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4371)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4337)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4345)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4318)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6912)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6886)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6843)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7030)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:186)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:325)
        at android.os.Looper.loop(Looper.java:142)
        at android.app.ActivityThread.main(ActivityThread.java:6537)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:857)

**Comment by likaiyuan559** [comment]
You can't change my package name when you use my so.

**Comment by likaiyuan559** [comment]
com.heyhou.social.video.HeyhouVideo,not change.

**Comment by likaiyuan559** [comment]
and com.heyhou.social.video.HeyhouRecorder

**Comment by anonym2** [comment]
How can I convert your project into a library so I can add it to mine?
