### ISSUE TITLE
楼主             mHeyhouVideo.getMetaInfo(mVideoPath,mateInfo)出错 是不是必须包名必须是你的

### ISSUE THREAD

**Issue by 13235388830** [likaiyuan559/TikTokDemo#20]
java.lang.UnsatisfiedLinkError: No implementation found for void com.uhome.uclient.main.record.crop.HeyhouVideo.getMetaInfo(java.lang.String, com.uhome.uclient.main.record.crop.VideoMetaInfo) (tried Java_com_uhome_uclient_main_record_crop_HeyhouVideo_getMetaInfo and Java_com_uhome_uclient_main_record_crop_HeyhouVideo_getMetaInfo__Ljava_lang_String_2Lcom_uhome_uclient_main_record_crop_VideoMetaInfo_2)
        at com.uhome.uclient.main.record.crop.HeyhouVideo.getMetaInfo(Native Method)
        at com.uhome.uclient.main.record.crop.VideoCropViewBar.setVideoPath(VideoCropViewBar.java:111)
        at com.uhome.uclient.main.record.activity.VideoEditActivity.main(VideoEditActivity.java:311)
        at com.uhome.uclient.base.BaseActivity.main(BaseActivity.java:60)
        at com.uhome.uclient.base.BaseActivity.onCreate(BaseActivity.java:51)
        at android.app.Activity.performCreate(Activity.java:6758)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1122)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2806)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2918)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1628)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:203)

**Comment by 13235388830** [comment]
可以加一下微信吗   我想集成自己的项目中

**Comment by likaiyuan559** [comment]
包名必须是我的，集成到项目中新建一个同类包名就可以了，或者新建一个moudle，保持包名一致。
