### ISSUE TITLE
魅族5.1手机上闪退怎么回事呢

### ISSUE THREAD

**Issue by wangshilsj** [likaiyuan559/TikTokDemo#7]
各位大神 魅族5.1手机上闪退怎么回事，找不到so库

**Comment by likaiyuan559** [comment]
请附上错误信息

**Comment by wangshilsj** [comment]
FATAL EXCEPTION: Thread-2273
                                                                               Process: com.tiktokdemo.lky.tiktokdemo, PID: 14382
                                                                               java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.tiktokdemo.lky.tiktokdemo-1/base.apk", zip file "/data/app/com.tiktokdemo.lky.tiktokdemo-1/split_lib_dependencies_apk.apk", zip file "/data/app/com.tiktokdemo.lky.tiktokdemo-1/split_lib_slice_0_apk.apk", zip file "/data/app/com.tiktokdemo.lky.tiktokdemo-1/split_lib_slice_1_apk.apk", zip file "/data/app/com.tiktokdemo.lky.tiktokdemo-1/split_lib_slice_2_apk.apk", zip file "/data/app/com.tiktokdemo.lky.tiktokdemo-1/split_lib_slice_3_apk.apk", zip file "/data/app/com.tiktokdemo.lky.tiktokdemo-1/split_lib_slice_4_apk.apk", zip file "/data/app/com.tiktokdemo.lky.tiktokdemo-1/split_lib_slice_5_apk.apk", zip file "/data/app/com.tiktokdemo.lky.tiktokdemo-1/split_lib_slice_6_apk.apk", zip file "/data/app/com.tiktokdemo.lky.tiktokdemo-1/split_lib_slice_7_apk.apk", zip file "/data/app/com.tiktokdemo.lky.tiktokdemo-1/split_lib_slice_8_apk.apk", zip file "/data/app/com.tiktokdemo.lky.tiktokdemo-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.tiktokdemo.lky.tiktokdemo-1/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libopenh264.so"
                                                                                   at java.lang.Runtime.loadLibrary(Runtime.java:367)
                                                                                   at java.lang.System.loadLibrary(System.java:988)
                                                                                   at com.heyhou.social.video.HeyhouVideo.<clinit>(HeyhouVideo.java:13)
                                                                                   at com.tiktokdemo.lky.tiktokdemo.record.presenter.RecordVideoPresenter$10.run(RecordVideoPresenter.java:795)
                                                                                   at java.lang.Thread.run(Thread.java:818)



报错主要指向下面这几行代码
System.loadLibrary("openh264");
System.loadLibrary("ffmpeg");
System.loadLibrary("yuv");
System.loadLibrary("heyhou_video");
