### ISSUE TITLE
魅族5.1手机上闪退怎么回事，找不到so库

### ISSUE THREAD

**Issue by wangshilsj** [likaiyuan559/TikTokDemo#8]
FATAL EXCEPTION: Thread-2273
                                                                               Process: com.tiktokdemo.lky.tiktokdemo, PID: 14382
                                                                               java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.tiktokdemo.lky.tiktokdemo-1/base.apk", zip file "/data/app/com.tiktokdemo.lky.tiktokdemo-1/split_lib_dependencies_apk.apk", zip file "/data/app/com.tiktokdemo.lky.tiktokdemo-1/split_lib_slice_0_apk.apk", zip file "/data/app/com.tiktokdemo.lky.tiktokdemo-1/split_lib_slice_1_apk.apk", zip file "/data/app/com.tiktokdemo.lky.tiktokdemo-1/split_lib_slice_2_apk.apk", zip file "/data/app/com.tiktokdemo.lky.tiktokdemo-1/split_lib_slice_3_apk.apk", zip file "/data/app/com.tiktokdemo.lky.tiktokdemo-1/split_lib_slice_4_apk.apk", zip file "/data/app/com.tiktokdemo.lky.tiktokdemo-1/split_lib_slice_5_apk.apk", zip file "/data/app/com.tiktokdemo.lky.tiktokdemo-1/split_lib_slice_6_apk.apk", zip file "/data/app/com.tiktokdemo.lky.tiktokdemo-1/split_lib_slice_7_apk.apk", zip file "/data/app/com.tiktokdemo.lky.tiktokdemo-1/split_lib_slice_8_apk.apk", zip file "/data/app/com.tiktokdemo.lky.tiktokdemo-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.tiktokdemo.lky.tiktokdemo-1/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libopenh264.so"
                                                                                   at java.lang.Runtime.loadLibrary(Runtime.java:367)
                                                                                   at java.lang.System.loadLibrary(System.java:988)
                                                                                   at com.heyhou.social.video.HeyhouVideo.<clinit>(HeyhouVideo.java:13)
                                                                                   at com.tiktokdemo.lky.tiktokdemo.record.presenter.RecordVideoPresenter$10.run(RecordVideoPresenter.java:795)
                                                                                   at java.lang.Thread.run(Thread.java:818)

**Comment by likaiyuan559** [comment]
demo直接跑的话是否是正常的？你自己移植的话请查看你build.gradle中的jniLibs是否定位正确。

**Comment by wangshilsj** [comment]
demo运行起来没问题，点击录制按钮的时候魅族5.1手机闪退，在其他手机上没问题，build.gradle的配置也是根据demo来的

**Comment by likaiyuan559** [comment]
Demo在魅族5.1上跑会闪退吗？

**Comment by wangshilsj** [comment]
会的

**Comment by wangshilsj** [comment]
会的

**Comment by wangshilsj** [comment]
会的

**Comment by likaiyuan559** [comment]
手机型号请告知我一下

**Comment by wangshilsj** [comment]
好的 现在手机没在手上 我明天上班给您发一下吧 非常感谢啊

**Comment by wangshilsj** [comment]
好的 现在手机没在手上 我明天上班给您发一下吧 非常感谢啊

**Comment by wangshilsj** [comment]
好的 现在手机没在手上 我明天上班给您发一下吧 非常感谢啊

**Comment by wangshilsj** [comment]
魅蓝2手机 5.1的系统
